sudo: required

services:
  - docker

before_install:
  - docker build -t khang6294/fullstack-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run khang6294/fullstack-docker npm run test -- --coverage

after_success:
  - docker build -t khang6294/fullstack-docker-client ./client
  - docker build -t khang6294/fullstack-docker-nginx ./nginx
  - docker build -t khang6294/fullstack-docker-server ./server
  - docker build -t khang6294/fullstack-docker-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push khang6294/fullstack-docker-client
  - docker push khang6294/fullstack-docker-nginx
  - docker push khang6294/fullstack-docker-server
  - docker push khang6294/fullstack-docker-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "fullstack-docker"
  env: "FullstackDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-905141291592"
  bucket_path: "fullstack-docker"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"